/* DEALER PREMIUM — source-of-truth configuration, preserving the Restaurant Studio schema for compatibility. */
window.RestaurantDefaults={
  id:'dealer-premium-class1',schemaVersion:4,status:'draft',
  brand:{name:'NOVA MOTORS',logoText:'NOVA MOTORS',accent:'#d8ff4f',ink:'#0a0a0a',paper:'#f2f0eb',fontDisplay:'Italiana',fontBody:'DM Sans'},
  header:{links:[['Models','#signature'],['Philosophy','#story'],['Experience','#experience'],['Visit','#visit']],studioLabel:'Dealer Studio',reserveLabel:'Book a drive'},
  hero:{kicker:'Alicante · Premium electric mobility',line1:'NOVA',line2:'moves differently.',body:'A premium dealership experience built around the car, not around a catalogue. Three vehicles. One continuous stage.',cta:'Explore the models',stamp:'VEHICLE SHOWCASE · DEALER STUDIO ·',scroll:'SCROLL TO ENTER'},
  philosophy:{index:'01 / Philosophy',title:'The vehicle enters the scene as an object of desire, not as another card in a grid.',body1:'The dealership keeps the same premium architecture as the restaurant donor: editorial composition, controlled media, persistent Studio and product-led motion.',body2:'We replace the plate with the vehicle while preserving the original DNA: one active product, visual hierarchy, direct manipulation, detail view and project-level customisation.'},
  orbital:{index:'02 / Featured vehicles',kicker:'Drag · wheel · swipe · arrows',title:'The Vehicle Showcase',explore:'Discover vehicle'},
  origin:{index:'03 / Design',title:'Designed around the journey.',body:'Every model combines proportion, aerodynamics and technology into a coherent object. The interface treats specifications as part of the story, not as secondary data.',caption:'Design · Engineering · Detail'},
  atmosphere:{index:'04 / Experience',title:'Electric becomes emotional.',caption:'Road · cabin · silence',body:'Acceleration, range, material quality and software become one experience before the first kilometre.',cta:'Book a test drive →'},
  chef:{index:'05 / Guidance',title:'Advice without noise.',quote:'“The best car is not the most expensive one. It is the one that fits the way you actually move.”',badges:['Independent guidance','Transparent comparison','Test-drive first']},
  visit:{kicker:'Alicante · Mon — Sat',title:'Take the wheel.',cta:'Book a test drive',addressLabel:'Showroom',address:'Alicante · Costa Blanca',serviceLabel:'Opening',service:'09:30 — 19:30',contactLabel:'Contact',contact:'hello@novamotors.demo',bookingUrl:'#'},
  footer:{left:'NOVA MOTORS',center:'Premium Dealer Studio',right:'Interactive dealership prototype'},
  motion:{orbitalStyle:'dealer',text:{hero:'cinematic',philosophy:'line',origin:'soft',atmosphere:'editorial',chef:'mask',visit:'rise'},media:{hero:'still',origin:'still',atmosphere:'still',chef:'still'}},
  media:{hero:{type:'image',url:'',fit:'cover',position:'50% 50%'},origin:{type:'image',url:'',fit:'cover',position:'50% 50%'},atmosphere:{type:'image',url:'',fit:'cover',position:'50% 50%'},chef:{type:'image',url:'',fit:'cover',position:'50% 50%'}},
  dishes:[
    {id:'vehicle-01',name:'Model S',meta:'Dual Motor · 634 km range · AWD',short:'Long-range electric grand tourer with instant response, low drag and a cabin built around distance.',price:'From €94,990',image:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260826_072108_3386a1a4-fbf8-450b-80f9-3120cb013f96.png',ingredients:'634 km WLTP · AWD · 5 seats · fast charging',origin:'Premium electric fastback',technique:'0–100 km/h from 3.2 s',pairing:'Long distance · executive travel',note:'The flagship: low, fast and designed to cover distance without drama.',allergens:'Test drive recommended before configuration',enabled:true},
    {id:'vehicle-02',name:'Model X',meta:'Dual Motor · 576 km range · AWD',short:'A spacious electric SUV with panoramic visibility, serious performance and room for the whole journey.',price:'From €99,990',image:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260826_072108_48afab8a-ae05-47f4-8159-962ab4a47430.png',ingredients:'576 km WLTP · AWD · up to 7 seats · fast charging',origin:'Premium electric SUV',technique:'0–100 km/h from 3.9 s',pairing:'Family · travel · space',note:'The most versatile car in the line-up when space matters as much as performance.',allergens:'Configuration varies by seating layout',enabled:true},
    {id:'vehicle-03',name:'Model Y',meta:'Long Range · 600 km class · AWD',short:'The balanced crossover: efficient packaging, everyday usability and the same clean electric response.',price:'From €48,990',image:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260826_072108_a8cd3fe5-5e51-4dac-9ba1-b790ae1b7ddd.png',ingredients:'Long Range · AWD · 5 seats · fast charging',origin:'Electric crossover',technique:'Low centre of gravity · instant torque',pairing:'Daily use · family · commuting',note:'The easiest point of entry when one car has to do almost everything.',allergens:'Range depends on version and wheel choice',enabled:true}
  ]
};
/* Isolate persistence from the donor restaurant while reusing its proven Store implementation. */
(() => {if(!window.RestaurantStore)return;const KEY='dealer-premium-class1',S=window.RestaurantStore,save=S.saveProject.bind(S),load=S.loadProject.bind(S),clear=S.clearProject.bind(S);S.saveProject=project=>save({...project,id:KEY});S.loadProject=()=>load(KEY);S.clearProject=()=>clear(KEY);})();
/* Load Dealer-specific visuals/assets/runtime without replacing the donor HTML or its persistence engine. */
(() => {const link=document.createElement('link');link.rel='stylesheet';link.href='dealer-premium.css';document.head.appendChild(link);['dealer-assets.js','dealer-runtime.js'].forEach(src=>{const s=document.createElement('script');s.src=src;s.async=false;document.head.appendChild(s)});})();