/* NOVA MOTORS — dealership source of truth. Donor field names remain only for runtime compatibility. */
window.RestaurantDefaults={
  id:'dealer-premium-class5',schemaVersion:5,status:'draft',
  brand:{name:'NOVA MOTORS',logoText:'NOVA MOTORS',accent:'#d8ff4f',ink:'#0a0a0a',paper:'#f2f0eb',fontDisplay:'Italiana',fontBody:'DM Sans'},
  header:{links:[['Models','#signature'],['Why NOVA','#story'],['Experience','#experience'],['Showroom','#visit']],studioLabel:'Dealer Studio',reserveLabel:'Book a test drive'},
  hero:{kicker:'Alicante · Premium electric vehicles',line1:'DRIVE',line2:'what moves you.',body:'Six distinctive electric cars. One place to compare them properly, understand what changes from model to model and decide from the driver’s seat.',cta:'Explore the collection',stamp:'DESIGN · PERFORMANCE · RANGE ·',scroll:'DISCOVER THE COLLECTION'},
  philosophy:{index:'01 / Why NOVA',title:'The right car is the one that makes sense before you even turn the key.',body1:'At NOVA, the conversation starts with how you drive: city or motorway, family or solo, comfort or performance, daily range or long-distance freedom.',body2:'Then we compare the cars that genuinely fit. Clear specifications, meaningful differences and a test drive before the decision.'},
  orbital:{index:'02 / Collection',kicker:'Drag · wheel · swipe · arrows',title:'Choose your next drive.',explore:'View vehicle'},
  origin:{index:'03 / Design & engineering',title:'Every proportion has a purpose.',body:'Aerodynamics, packaging, battery placement and cabin architecture shape more than the silhouette. They determine efficiency, stability, space and the way a car feels from the first metre.',caption:'AERODYNAMICS · MATERIALS · ENGINEERING'},
  atmosphere:{index:'04 / Driving experience',title:'Performance you feel before you measure it.',caption:'ACCELERATION · SILENCE · CONTROL',body:'Instant torque is only the beginning. Steering response, ride quality, visibility, braking confidence, software and cabin refinement decide whether a car works for you every day.',cta:'Book a test drive →'},
  chef:{index:'05 / Expert guidance',title:'Compare the differences that actually matter.',quote:'“Range, power and price are easy to print. The real job is understanding which combination fits the way you live and drive.”',badges:['Side-by-side comparison','Transparent specifications','Test-drive first']},
  visit:{kicker:'Alicante · Monday — Saturday',title:'The next decision belongs behind the wheel.',cta:'Book a test drive',addressLabel:'Showroom',address:'Alicante · Costa Blanca',serviceLabel:'Opening hours',service:'09:30 — 19:30',contactLabel:'Sales & test drives',contact:'hello@novamotors.demo',bookingUrl:'#'},
  footer:{left:'NOVA MOTORS',center:'Electric vehicles · Alicante',right:'Compare · Drive · Decide'},
  motion:{orbitalStyle:'dealer',dishJourney:false,text:{hero:'cinematic',philosophy:'line',origin:'soft',atmosphere:'editorial',chef:'mask',visit:'rise'},media:{hero:'still',origin:'still',atmosphere:'still',chef:'still'}},
  media:{
    hero:{type:'image',url:'imagenes/hf_20260826_072108_3386a1a4-fbf8-450b-80f9-3120cb013f96.png',fit:'contain',position:'72% 54%'},
    origin:{type:'image',url:'imagenes/hf_20260826_082019_1d9402df-f6d2-4ab4-8336-36a07550c0df.png',fit:'contain',position:'50% 58%'},
    atmosphere:{type:'image',url:'imagenes/hf_20260826_072108_48afab8a-ae05-47f4-8159-962ab4a47430.png',fit:'contain',position:'50% 56%'},
    chef:{type:'image',url:'imagenes/hf_20260826_082019_42e21187-79f3-4ae0-87a3-8a085300b009.png',fit:'contain',position:'50% 57%'}
  },
  dishes:[
    {id:'vehicle-01',name:'Model S',meta:'Dual Motor · 634 km range · AWD',short:'A low, long-range electric grand tourer built for effortless motorway pace, instant response and quiet distance.',price:'From €94,990',image:'imagenes/hf_20260826_072108_3386a1a4-fbf8-450b-80f9-3120cb013f96.png',ingredients:'634 km WLTP · AWD · 5 seats · fast charging',origin:'Premium electric fastback',technique:'0–100 km/h from 3.2 s',pairing:'Long-distance travel · executive use',note:'Choose it when range, refinement and effortless speed matter more than SUV packaging.',allergens:'Confirm current market specification and availability before order',enabled:true},
    {id:'vehicle-02',name:'Model X',meta:'Dual Motor · 576 km range · AWD',short:'A large electric SUV combining serious acceleration, panoramic visibility and flexible space for longer journeys.',price:'From €99,990',image:'imagenes/hf_20260826_072108_48afab8a-ae05-47f4-8159-962ab4a47430.png',ingredients:'576 km WLTP · AWD · up to 7 seats · fast charging',origin:'Premium electric SUV',technique:'0–100 km/h from 3.9 s',pairing:'Family travel · passengers · luggage',note:'The strongest fit when you need genuine space without giving up electric performance.',allergens:'Seating layouts and specifications vary by market',enabled:true},
    {id:'vehicle-03',name:'Model Y',meta:'Long Range · 600 km class · AWD',short:'A versatile electric crossover that balances usable space, efficiency, easy access and everyday performance.',price:'From €48,990',image:'imagenes/hf_20260826_072108_a8cd3fe5-5e51-4dac-9ba1-b790ae1b7ddd.png',ingredients:'Long Range · AWD · 5 seats · fast charging',origin:'Electric crossover',technique:'Low centre of gravity · instant torque',pairing:'Daily use · family · commuting',note:'A convincing all-rounder when one car has to cover commuting, family use and longer trips.',allergens:'Range changes with version, wheels, weather and driving conditions',enabled:true},
    {id:'vehicle-04',name:'Model 3 Performance',meta:'Performance · AWD · sport chassis',short:'A compact electric sports saloon tuned for sharper response, stronger acceleration and everyday usability.',price:'From €57,490',image:'imagenes/hf_20260826_082019_42e21187-79f3-4ae0-87a3-8a085300b009.png',ingredients:'AWD · adaptive damping · sport seats · fast charging',origin:'Performance electric saloon',technique:'0–100 km/h in the low-3-second class',pairing:'Driver focus · daily performance',note:'The choice for drivers who want the smallest, most responsive performance car in the collection.',allergens:'Performance figures vary by market, tyres and configuration',enabled:true},
    {id:'vehicle-05',name:'Cybertruck',meta:'Stainless steel · AWD · utility',short:'A radically shaped electric utility vehicle focused on durability, cargo capacity and unconventional engineering.',price:'Market dependent',image:'imagenes/hf_20260826_082019_1d9402df-f6d2-4ab4-8336-36a07550c0df.png',ingredients:'Stainless-steel body · AWD · utility bed · high ground clearance',origin:'Electric utility vehicle',technique:'Steer-by-wire · high-output electric drivetrain',pairing:'Utility · adventure · statement design',note:'Consider it for capability and character first; its size, format and market availability make it a very different ownership proposition.',allergens:'Availability and homologation depend on market',enabled:true},
    {id:'vehicle-06',name:'Roadster',meta:'Concept · electric supercar · 2+2',short:'A low electric sports-car concept built around extreme acceleration, compact proportions and halo-car ambition.',price:'Future model',image:'imagenes/hf_20260826_082019_ef284aac-ec4a-430d-bdb4-7aeec8b6cc4b.png',ingredients:'2+2 layout · low-drag body · performance battery architecture',origin:'Electric sports-car concept',technique:'High-performance all-electric drivetrain',pairing:'Performance · design · halo product',note:'Treat it as the emotional extreme of the range rather than a direct alternative to the everyday models.',allergens:'Future/concept model; final production specification may change',enabled:true}
  ]
};
(() => {const D=window.RestaurantDefaults;let footerValue=D.footer;Object.defineProperty(D,'footer',{enumerable:true,configurable:true,get(){return footerValue},set(next){const text=String(next?.center||'');if(/Class\s*06|Restaurant Product/i.test(text))return;footerValue=next}})})();
(() => {if(!window.RestaurantStore)return;const KEY='dealer-premium-class5',S=window.RestaurantStore,save=S.saveProject.bind(S),load=S.loadProject.bind(S),clear=S.clearProject.bind(S);S.saveProject=project=>save({...project,id:KEY});S.loadProject=()=>load(KEY);S.clearProject=()=>clear(KEY);})();
(() => {const link=document.createElement('link');link.rel='stylesheet';link.href='dealer-premium.css';document.head.appendChild(link);['dealer-assets.js','dealer-motion-bridge.js','dealer-runtime.js'].forEach(src=>{const s=document.createElement('script');s.src=src;s.async=false;document.head.appendChild(s)});})();